main.tf 파일에서 5개의 모듈을 호출하도록 변경
opsnow-tools/valve-eks pull request #21
Opened 2019-11-27 05:45 UTC by ounju

main.tf 파일에서 5개의 모듈을 호출하도록 변경했습니다.
모듈도 일부 변경했습니다.
기존에 data 테그를 이용해 리소스 정보를 가져오는 부분을 제거하고, 모듈의 output 에서 정보를 가져오는 방식으로 변경했습니다.

2019-11-27 05:49 UTC, MuYoul approved these changes

2019-11-27 05:58 UTC, longlg88 commented on example/eks-fast-track/main.tf
> +module "vpc" {
main.tf 에는 module에서 어떤 값을 수정해야하는지에 대한 주석이 필요해 보입니다.

2019-11-27 06:01 UTC, longlg88 commented on example/eks-fast-track/main.tf
> +module "vpc" {
왠지 가이드를 작성하셨을 수도 있을 것 같긴합니다만.. ㅎㅎ

2019-11-27 06:03 UTC, longlg88 commented on example/eks-fast-track/terraform.tfvars.sample
> +on_demand_base = "0"
tfvars에 on demand에 대한 주석도 필요해 보입니다.

2019-11-27 06:04 UTC, longlg88 commented on example/eks-fast-track/terraform.tfvars.sample
> +mixed_instances = ["m4.large", "r4.large", "r5.large"]
tfvars에 mixed_instances에 대한 동작 방식을 간단하게 언급했으면 좋겠습니다.

2019-11-27 06:05 UTC, longlg88 commented on example/eks-fast-track/terraform.tfvars.sample
> +weighted_routing = 100
weighted_routing 값이 꼭 100이 아니어도 됩니다. 이에 대한 주석을 간단하게 작성했으면 좋겠습니다. AWS route53의 weight 방식의 주소를 남겨도 좋을 것 같습니다.

2019-11-27 06:08 UTC, longlg88 commented on example/eks-fast-track/terraform.tfvars.sample
> +aws_region = "ap-northeast-2"
city stage name에 대한 정의도 언급했으면 합니다.
name은 닉네임이라기 보다는 클러스터 이름이라고 할 수 있습니다.

2019-11-27 06:11 UTC, MuYoul commented on example/eks-fast-track/main.tf
> +      rolearn  = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/SEOUL-SRE-K8S-BASTION"
aws에 role이 없는 유저의 경우 문제가 될 수 있음

2019-11-27 06:12 UTC, MuYoul commented on example/eks-fast-track/main.tf
> +    "kubernetes.io/cluster/seoul-sre-demo-eks"  = "shared"
tags는 동작하는데 문제는 없지만 바꾸는 것이 좋지 않을까요?

2019-11-27 06:13 UTC, MuYoul commented on example/eks-fast-track/main.tf
> +module "vpc" {
> 왠지 가이드를 작성하셨을 수도 있을 것 같긴합니다만.. ㅎㅎ

예상하신대로 가이드 작성되어서 나갑니다 :)

2019-11-27 06:29 UTC, MuYoul commented on example/eks-fast-track/terraform.tfvars.sample
> +min = "1"
최초 실행시 노드가 1개일 경우 느리게 동작할 수 있으니 2개로 바꾸는 건 어떨까요?

2019-11-27 06:31 UTC, MuYoul commented on example/eks-fast-track/terraform.tfvars.sample
> +weighted_routing = 100
https://docs.aws.amazon.com/ko_kr/Route53/latest/DeveloperGuide/routing-policy.html
가중치 기반 라우팅

2019-11-27 06:34 UTC, longlg88 requested changes
코멘트들 확인 바랍니다.

2019-11-27 08:12 UTC, ounju commented on example/eks-fast-track/terraform.tfvars.sample
> +on_demand_base = "0"
다음과 같이 수정하도록 하겠습니다.

# 쿠버네티스 워크노드에 대한 오토스케일링 그룹 설정,  온 디멘드 EC2 갯수 설정
# Absolute minimum amount of desired capacity that must be fulfilled by on-demand instances.
on_demand_base = "0"

# 쿠버네티스 워크노드에 대한 오토스케일링 그룹 설정,  온 디멘드 EC2 비율 설정
# Percentage split between on-demand and Spot instances above the base on-demand capacity.
on_demand_rate = "0"

2019-11-27 08:56 UTC, ounju commented on example/eks-fast-track/terraform.tfvars.sample
> +mixed_instances = ["m4.large", "r4.large", "r5.large"]
다음과 같이 수정하도록 하겠습니다.

\# 쿠버네티스 워크노드에 대한 설정
\# The type of the instance.
instance_type = "m5.large"

\# instance_type에 해당하는 EC2가 없는 경우 아래에 설정된 타입 중 하나를 대신 생성한다.
mixed_instances = ["m4.large", "r4.large", "r5.large"]

2019-11-27 09:10 UTC, ounju commented on example/eks-fast-track/terraform.tfvars.sample
> +weighted_routing = 100
다음과 같이 주석 추가하도록 하겠습니다.

\# 가중치 기반 라우팅 정책, 1~255 사이의 값 설정 가능
\# https://docs.aws.amazon.com/ko_kr/Route53/latest/DeveloperGuide/routing-policy.html#routing-policy-weighted
weighted_routing = 100

2019-11-27 09:18 UTC, ounju commented on example/eks-fast-track/terraform.tfvars.sample
> +aws_region = "ap-northeast-2"
다음과 같이 수정합니다.

\# 리소스 이름에 의미있는 정보를 담기위해 아래 3개의 변수를 연결하여 하나의 변수로 만들어서 사용함.
\# ex) full_name = city + stage + name
city   = "SEOUL"
stage  = "SRE"
name   = "FASTTRACK"    # 그냥 사용해도 되지만 유니크한 이름으로 변경해도 됨

2019-11-28 02:05 UTC, ounju commented on example/eks-fast-track/main.tf
> +    "kubernetes.io/cluster/seoul-sre-demo-eks"  = "shared"
다음과 같이 수정하겠습니다.

  tags = {
    "kubernetes.io/cluster/${lower(var.city)}-${lower(var.stage)}-${lower(var.name)}-eks"  = "shared"
  }

2019-11-28 02:09 UTC, ounju commented on example/eks-fast-track/terraform.tfvars.sample
> +min = "1"
비용 절약을 위해 일단 1개로 설정하고 상황 봐 가면서 숫자는 늘리는걸로 하죠~

2019-11-28 02:23 UTC, longlg88 commented on example/eks-fast-track/terraform.tfvars.sample
> +mixed_instances = ["m4.large", "r4.large", "r5.large"]
# 쿠버네티스 워크노드에 대한 설정
# The type of the instance.
instance_type = "m5.large"

# mixed_instances에는 위 instance_type 외에 타입을 추가해야 한다.
# mixed 설정이 있을 때, Default instance_type 외에 mixed_instances 타입으로 추가로 생성한다.
mixed_instances = ["m4.large", "r4.large", "r5.large"]

2019-11-28 02:25 UTC, longlg88 commented on example/eks-fast-track/main.tf
> +      rolearn  = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/SEOUL-SRE-K8S-BASTION"
@MuYoul 님 말씀처럼 Role이 없는 유저는 에러가 생길 수 있습니다.

새로운 User를 IAM에 등록하고 테스트를 해야 할 것 같아보입니다.
@ounju  님 확인 부탁드립니다.

2019-11-28 02:26 UTC, longlg88 commented on example/eks-fast-track/terraform.tfvars.sample
> +min = "1"
1개면 괜찮을 것 같습니다.

2019-11-28 02:26 UTC, longlg88 commented
추가로 코멘트 남겼습니다. 확인 바랍니다. @ounju

2019-11-28 02:28 UTC, longlg88 commented on example/eks-fast-track/terraform.tfvars.sample
> +mixed_instances = ["m4.large", "r4.large", "r5.large"]
@ounju  님 확인 부탁드립니다.

2019-11-28 05:19 UTC, gelius7 approved these changes
일단 전체 동작은 확인했습니다.
주석관련 코멘트들 처리되면 머지해도 되겠습니다.

2019-11-28 05:20 UTC, ounju commented on example/eks-fast-track/main.tf
> +      rolearn  = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/SEOUL-SRE-K8S-BASTION"
다음과 같이 설명 추가하도록 하겠습니다.

  # AWS EC2(Bastion)에서 terraform을 실행하기 위한 설정.
  # map_users 설정에 IAM 사용자 정보를 설정하고 IAM 사용자 권한으로 terraform 실행하는 경우는 필요 없음.
  map_roles = [
    {
      # AWS IAM Role, 사전에 생성되어 있어야 함. AdministratorAccess 정책이 맵핑되어 있어야 함.
      rolearn  = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/SEOUL-SRE-K8S-BASTION"
      # 쿠버네티스 RBAC 사용자이름, 기본값이므로 그냥 사용.
      username = "iam_role_bastion"
      # 쿠버네티스 RBAC 그룹, 기본값이므로 그냥 사용.
      group    = "system:masters"
    },
  ]

2019-11-28 05:37 UTC, ounju commented
보완해서 소스 올렸습니다.
승인해 주세요~~

2019-11-29 00:49 UTC, longlg88 approved these changes

2019-11-29 00:50 UTC, longlg88 commented
머지가 안되네요.. 흠

2019-11-29 04:17 UTC, MuYoul commented on example/eks-fast-track/main.tf
> +  name   = "${var.name}"
name이 무엇에 대한 name인지 알 수 없습니다.
이 name은 cluster의 이름으로 사용됩니다.  그러므로 cluster_name과 같이 바꾸는 것이 좋을 것 같습니다.

2019-11-29 04:24 UTC, ounju commented on example/eks-fast-track/terraform.tfvars.sample
> +mixed_instances = ["m4.large", "r4.large", "r5.large"]
바꾸도록 하겠습니다.

2019-11-29 04:28 UTC, ounju commented on example/eks-fast-track/main.tf
> +  name   = "${var.name}"
변수이름을 cluster_name 으로 변경하도록 하겠습니다.

2019-11-29 05:43 UTC, ounju commented
소스 코드 보완해서 올렸습니다. 리뷰해 주세요~

2019-12-02 04:28 UTC, gelius7 commented
모두 완료된것 같네요. 머지하겠습니다.

2019-12-02 04:28 UTC, merged