Feature add alertnow integration
opsnow-tools/valve-eks pull request #7
Opened 2019-09-02 06:59 UTC by pakisto

2019-09-03 04:04 UTC, longlg88 commented on example/alertnow-integration/main.tf
> +    bucket = "valve-eks-example"
테스트 용도로 하는 것인가요?

2019-09-03 04:07 UTC, longlg88 commented
namespace 명은 나중에 바꾸게 되는 것인가요?
- AWS/EC2 
- AWS/ES
등등 있었습니다.

2019-09-03 04:08 UTC, longlg88 requested changes
피드백 확인바랍니다~

2019-09-03 08:42 UTC, longlg88 requested changes
피드백 확인 바랍니다.

2019-09-03 08:43 UTC, longlg88 reviewed
.

2019-09-19 02:27 UTC, gelius7 approved these changes
확인했습니다.

2019-10-31 02:24 UTC, pakisto commented
> namespace 명은 나중에 바꾸게 되는 것인가요?
> 
> * AWS/EC2
> * AWS/ES
>   등등 있었습니다.

이건 CloudWatch 메트릭 알람 설정에 필요한 메트릭 네임스페이스입니다. k8s 메트릭과 다른 것입니다. (구두로 설저명한바 있습니다.)

2019-10-31 02:26 UTC, longlg88 approved these changes
확인했습니다.

2019-10-31 02:26 UTC, merged