modify local file path
opsnow-tools/valve-eks pull request #9
Opened 2019-09-18 04:00 UTC by longlg88

2019-09-19 00:55 UTC, gelius7 commented
해당 경로는 특수합니다
여기서 수정할 내용은 아니라고 생각합니다
아니면 또 다른 아이디어가 있어야 합니다

2019-09-19 00:57 UTC, gelius7 requested changes
특수한 경로입니다. 다시 생각해봅시다

2019-09-19 01:22 UTC, gelius7 commented
output path 를 variable 로 받는건 어떨까요?

2019-09-23 02:23 UTC, longlg88 commented
변경 부분 정리
- main.tf
  -  `enable_eks_config_custom_path` bool 변수 / `eks_config_path` string 변수 추가 
    - `enable_eks_config_custom_path` default 값은 false이며, false일 시 path.cwd를 사용
    - true일 경우 eks_config_path 값을 읽어 경로 세팅

- 91-localfile.tf
  - variable eks_config_path / enable_eks_config_custom_path 정의
  - filename을 bool 변수로 비교하여 path 조정

2019-09-23 02:37 UTC, gelius7 approved these changes
확인했습니다

2019-09-25 06:16 UTC, pakisto approved these changes

2019-09-25 06:16 UTC, merged